#!/bin/bash

# Script to delete all unnecessary files

# Delete all Git and .pyc files
cd ..
rm ./.gitignore
rm -r -f ./.git/
find . -name \*.pyc -delete

# Remove STAN files from fixed revisions
rm -r ./fixed_revisions/derived_data/STAN_models/

# Remove output files
rm -r ./code/python/simulation/output/
rm -r ./code/python/regressions/output/
rm -r ./code/python/get_graphs/output/
rm -r ./code/python/estimate_R/output/
rm -r ./code/python/construct_dataset/output/
rm -r ./code/python/download_data/output/

# Remove script itself
rm ./scripts/clean_repository