#!/bin/bash

# Run time: ~6 hours (+7.5 hours for mismeasurement Monte Carlo)

# Remove existing fixed data revisions (if any exist)
rm -r ../fixed_revisions/derived_data/
mkdir ../fixed_revisions/derived_data/
mkdir ../fixed_revisions/derived_data/dataset/
mkdir ../fixed_revisions/derived_data/R_estimates/
mkdir ../fixed_revisions/derived_data/KF_results/
mkdir ../fixed_revisions/derived_data/latex_input/
mkdir ../fixed_revisions/derived_data/STAN_models/

# Construct dataset for empirical analysis
echo "Constructing dataset"
cp ../fixed_revisions/original_data/time_series_covid19_confirmed_global.csv ../code/python/construct_dataset/input/
cp ../fixed_revisions/original_data/time_series_covid19_deaths_global.csv ../code/python/construct_dataset/input/
cp ../fixed_revisions/original_data/time_series_covid19_recovered_global.csv ../code/python/construct_dataset/input/
cd ../code/python
python3 -W ignore -m construct_dataset.construct_dataset
cp ./construct_dataset/output/dataset.csv ../../fixed_revisions/derived_data/dataset/

# Run unit tests on the constructed dataset
cd ./tests/
nosetests tests_dataset.py -v > tests_dataset.txt 2>&1
cd ..

# Estimate R using Kalman filter to obtain
# estimates of the variance of disturbances
# and signal-to-noise ratio (used for calibrating
# priors in Bayesian filtering with STAN)
echo "Getting Kalman filter estimates"
cd ./estimate_R
rm -r ./input/
mkdir ./input/
mkdir ./input/estimate_R_KF/
cp ../../../fixed_revisions/derived_data/dataset/dataset.csv ./input/estimate_R_KF/
cd ..
python3 -W ignore -m estimate_R.estimate_R_KF
cp ./estimate_R/output/estimate_R_KF/optim_res.csv ../../fixed_revisions/derived_data/KF_results/

# Estimate R using Bayesian filtering
echo "Constructing STAN models"
cd ./estimate_R
mkdir ./input/construct_STAN_models/
cp ../../../fixed_revisions/derived_data/KF_results/optim_res.csv ./input/construct_STAN_models/
cd ..
python3 -W ignore -m estimate_R.construct_STAN_models
cp ./estimate_R/output/construct_STAN_models/model_missing.pkl ../../fixed_revisions/derived_data/STAN_models/
cp ./estimate_R/output/construct_STAN_models/model_no_missing.pkl ../../fixed_revisions/derived_data/STAN_models/

echo "Estimating R with STAN"
cd ./estimate_R
mkdir ./input/estimate_R_STAN/
cp ../../../fixed_revisions/derived_data/dataset/dataset.csv ./input/estimate_R_STAN/
cp ../../../fixed_revisions/derived_data/STAN_models/model_missing.pkl ./input/estimate_R_STAN/
cp ../../../fixed_revisions/derived_data/STAN_models/model_no_missing.pkl ./input/estimate_R_STAN/
cd ..
python3 -W ignore -m estimate_R.estimate_R_STAN
cp ./estimate_R/output/estimate_R_STAN/estimated_R.csv ../../fixed_revisions/derived_data/R_estimates/

# Run unit tests on the estimates
cd ./tests/
nosetests tests_estimates.py -v > tests_estimates.txt 2>&1
cd ..

echo "Get example graph of filter vs smoother"
cd ./estimate_R
mkdir ./input/example_filter_smoother/
cp ../../../fixed_revisions/derived_data/dataset/dataset.csv ./input/example_filter_smoother/
cp ../../../fixed_revisions/derived_data/STAN_models/model_missing.pkl ./input/example_filter_smoother/
cp ../../../fixed_revisions/derived_data/STAN_models/model_no_missing.pkl ./input/example_filter_smoother/
cd ..
python3 -W ignore -m estimate_R.example_filter_smoother
cp ./estimate_R/output/example_filter_smoother/filter_smoother.pgf ../../fixed_revisions/derived_data/latex_input/

# Plot estimated R
echo "Plotting estimates"
cd ./get_graphs
rm -r ./input/
mkdir ./input/
cp ../../../fixed_revisions/derived_data/R_estimates/estimated_R.csv ./input/
cp ../../../fixed_revisions/derived_data/dataset/dataset.csv ./input/
cp ../../../fixed_revisions/original_data/interventions.csv ./input/
cd ..
python3 -W ignore -m get_graphs.plot_R
cp ./get_graphs/output/R/R_World.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./get_graphs/output/R/R_countries.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./get_graphs/output/R/R_countries_2.pgf ../../fixed_revisions/derived_data/latex_input/

echo "Get table of R0"
python3 -W ignore -m get_graphs.table_R0
cp ./get_graphs/output/table_R0/table_R0.txt ../../fixed_revisions/derived_data/latex_input/

echo "Get a plot of raw and smoothed growth rate"
python3 -W ignore -m get_graphs.plot_raw_growth_rate
cp ./get_graphs/output/plot_raw_growth_rate/raw_data_infected.pgf ../../fixed_revisions/derived_data/latex_input/

# Get regression results
echo "Estimating intervention regressions"
cd ./regressions
rm -r ./input/
mkdir ./input/
mkdir ./input/interventions/
cp ../../../fixed_revisions/derived_data/R_estimates/estimated_R.csv ./input/interventions/
cp ../../../fixed_revisions/original_data/full-list-daily-covid-19-tests-per-thousand.csv ./input/interventions/
cp ../../../fixed_revisions/original_data/interventions.csv ./input/interventions/
cp ../../../fixed_revisions/original_data/Global_Mobility_Report.csv ./input/interventions/
cd ..
python3 -W ignore -m regressions.interventions
cp ./regressions/output/interventions/event_study_case_based.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/event_study_lockdown.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/event_study_public.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/event_study_school_closure.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/event_study_social_distancing.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/interventions.txt ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/interventions_one_at_a_time.txt ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/interventions/regressions_dataset.csv ../../fixed_revisions/derived_data/dataset/
cp ./regressions/output/interventions/mobility.csv ../../fixed_revisions/derived_data/dataset/

echo "Getting mobility graphs"
cd ./regressions
mkdir ./input/mobility_graphs/
cp ../../../fixed_revisions/derived_data/dataset/regressions_dataset.csv ./input/mobility_graphs/
cp ../../../fixed_revisions/derived_data/dataset/mobility.csv ./input/mobility_graphs/
cp ../../../fixed_revisions/derived_data/R_estimates/estimated_R.csv ./input/mobility_graphs/
cd ..
python3 -W ignore -m regressions.mobility_graphs
cp ./regressions/output/mobility_graphs/event_study_mobility.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/mobility_graphs/mobility_scatter.pgf ../../fixed_revisions/derived_data/latex_input/

echo "Getting predictive scatterplot"
cd ./regressions
mkdir ./input/predictive/
cp ../../../fixed_revisions/derived_data/R_estimates/estimated_R.csv ./input/predictive/
cp ../../../fixed_revisions/derived_data/dataset/dataset.csv ./input/predictive/
cd ..
python3 -W ignore -m regressions.predictive
cp ./regressions/output/predictive/predictive_1.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/predictive/predictive_2.pgf ../../fixed_revisions/derived_data/latex_input/

echo "Correlating estimates with Cori et al method"
cd ./regressions
mkdir ./input/correlate_epiestim/
cp ../../../fixed_revisions/derived_data/R_estimates/estimated_R.csv ./input/correlate_epiestim/
cp ../../../fixed_revisions/original_data/R_EpiEstim.csv ./input/correlate_epiestim/
cd ..
python3 -W ignore -m regressions.correlate_epiestim
cp ./regressions/output/correlate_epiestim/correlate_epiestim.txt ../../fixed_revisions/derived_data/latex_input/

echo "Performing power analysis simulation"
cd ./regressions
mkdir ./input/power_study/
cp ../../../fixed_revisions/derived_data/dataset/regressions_dataset.csv ./input/power_study/
cd ..
python3 -W ignore -m regressions.power_study
cp ./regressions/output/power_study/power_study.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./regressions/output/power_study/parameters_power_study.txt ../../fixed_revisions/derived_data/latex_input/

# Perform Monte Carlo simulation on underdetection
echo "Running Monte Carlo simulation on underdetection"
cd ./mismeasurement
rm -r ./input/
mkdir ./input/
cp ../../../fixed_revisions/derived_data/R_estimates/estimated_R.csv ./input/
cp ../../../fixed_revisions/derived_data/STAN_models/model_missing.pkl ./input/
cp ../../../fixed_revisions/derived_data/STAN_models/model_no_missing.pkl ./input/
cd ..
python3 -W ignore -m mismeasurement.mismeasurement
cp ./mismeasurement/output/MC_mean_estimates.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./mismeasurement/output/MC_abs_error.pgf ../../fixed_revisions/derived_data/latex_input/
cp ./mismeasurement/output/MC_coverage_prob.pgf ../../fixed_revisions/derived_data/latex_input/

# Perform Monte Carlo simulation on SEIR model
echo "Running Monte Carlo simulation on SEIR model"
python3 -W ignore -m simulation.simulation
cp ./simulation/output/MC_SEIR.pgf ../../fixed_revisions/derived_data/latex_input/